//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation_History
    {
        public decimal Cancellation_Id { get; set; }
        public Nullable<decimal> Order_Id { get; set; }
        public Nullable<System.DateTime> Cancellation_Date { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsRefunded { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<decimal> Admin_Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Order_Details Order_Details { get; set; }
    }
}
