//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint_Questions
    {
        public decimal Question_Id { get; set; }
        public Nullable<decimal> Customer_Id { get; set; }
        public string Hint_Question { get; set; }
        public string Hint_Answer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
